"""Generate sensor-only wheel FK from the exact training MJCF; native fixtures included."""
import argparse,json,hashlib
from pathlib import Path
import numpy as np
import mujoco
p=argparse.ArgumentParser();p.add_argument('--model',type=Path,required=True);p.add_argument('--out',type=Path,required=True);p.add_argument('--fixtures',type=Path,required=True);a=p.parse_args()
m=mujoco.MjModel.from_xml_path(str(a.model));root=m.body('base_link').id
w=[m.geom('leg_'+k+'_3_wheel_collision').id for k in ['front_r','front_l','back_r','back_l']]
assert root==1 and m.njnt==13
I=np.eye(3)
def mat(q):
 out=np.empty(9);mujoco.mju_quat2Mat(out,q);return out.reshape(3,3)
body=[]
for b in range(m.nbody):
 row=-1;jpos=np.zeros(3)
 if m.body_jntnum[b] and b!=root:
  assert m.body_jntnum[b]==1
  j=m.body_jntadr[b];assert m.jnt_type[j]==mujoco.mjtJoint.mjJNT_HINGE
  np.testing.assert_allclose(m.jnt_axis[j],[0,0,1]);row=int(m.jnt_qposadr[j]-7);jpos=m.jnt_pos[j]
 body.append((int(m.body_parentid[b]),row,m.body_pos[b],mat(m.body_quat[b]),jpos))
def arr(x):return '{'+','.join(format(float(v),'.17g') for v in np.ravel(x))+'}'
s='''#pragma once
// Generated by scripts/notebook_lift/generate_geometry.py from training model.
#include <algorithm>
#include <array>
#include <cmath>
namespace notebook_alignment_v4 {
struct WheelGeometry {
 using V3=std::array<double,3>;using M3=std::array<double,9>;
 struct Body {int parent,joint;V3 pos;M3 rotation;V3 pivot;};
 static constexpr const char* model_sha256="'''+hashlib.sha256(a.model.read_bytes()).hexdigest()+'''";
 static constexpr std::array<Body,'''+str(m.nbody)+'''> bodies{{
'''
for parent,row,pos,R,jpos in body:s+='{'+f'{parent},{row},'+arr(pos)+','+arr(R)+','+arr(jpos)+'},\n'
s+='}};\nstatic constexpr std::array<int,4> wheel_body{'+','.join(str(int(m.geom_bodyid[g])) for g in w)+'};\n'
s+='static constexpr std::array<V3,4> wheel_pos{{'+','.join(arr(m.geom_pos[g]) for g in w)+'}};\n'
s+='static constexpr std::array<M3,4> wheel_rotation{{'+','.join(arr(mat(m.geom_quat[g])) for g in w)+'}};\n'
s+=''' static V3 add(V3 a,const V3& b){for(int i=0;i<3;++i)a[i]+=b[i];return a;}
 static V3 mv(const M3& a,const V3& v){V3 o{};for(int i=0;i<3;++i)for(int j=0;j<3;++j)o[i]+=a[3*i+j]*v[j];return o;}
 static M3 mul(const M3& a,const M3& b){M3 o{};for(int i=0;i<3;++i)for(int j=0;j<3;++j)for(int k=0;k<3;++k)o[3*i+j]+=a[3*i+k]*b[3*k+j];return o;}
 static std::array<double,4> bottoms(const std::array<double,12>& q,const V3& gravity){
  std::array<V3,bodies.size()> p{};std::array<M3,bodies.size()> R{};
  R[0]=R[1]=M3{1,0,0,0,1,0,0,0,1};
  for(unsigned b=2;b<bodies.size();++b){auto t=bodies[b];M3 local=t.rotation;V3 position=t.pos;
   if(t.joint>=0){double co=std::cos(q[t.joint]),si=std::sin(q[t.joint]);M3 spin{co,-si,0,si,co,0,0,0,1};auto offset=mv(spin,t.pivot);for(int i=0;i<3;++i)offset[i]=t.pivot[i]-offset[i];position=add(position,mv(local,offset));local=mul(local,spin);}
   p[b]=add(p[t.parent],mv(R[t.parent],position));R[b]=mul(R[t.parent],local);
  }
  std::array<double,4> out{};
  for(int k=0;k<4;++k){int b=wheel_body[k];auto center=add(p[b],mv(R[b],wheel_pos[k]));auto orient=mul(R[b],wheel_rotation[k]);double z=0,az=0;for(int i=0;i<3;++i){z-=center[i]*gravity[i];az-=orient[3*i+2]*gravity[i];}out[k]=z-.048*std::sqrt(std::max(0.,1-az*az))-.01675*std::abs(az);}
  return out;
 }
};
}
'''
a.out.write_text(s)
rng=np.random.default_rng(2417);rows=[]
for _ in range(256):
 d=mujoco.MjData(m);d.qpos[:7]=[0,0,0,1,0,0,0];d.qpos[7:]=rng.uniform(-.2,.2,12)+np.array([1,0,0,-1,0,0]*2);d.qpos[9::3]=rng.uniform(-100,100,4)
 mujoco.mj_forward(m,d);g=rng.normal(0,.08,3)+[0,0,-1];g/=np.linalg.norm(g);center=d.geom_xpos[w];axis=d.geom_xmat[w].reshape(4,3,3)[:,:,2];az=-axis@g;bottom=-center@g-.048*np.sqrt(np.maximum(1-az*az,0))-.01675*np.abs(az);rows.append(np.r_[d.qpos[7:],g,bottom])
np.savetxt(a.fixtures,rows,delimiter=',',fmt='%.17g')
print(json.dumps(dict(model_sha256=hashlib.sha256(a.model.read_bytes()).hexdigest(),bodies=m.nbody,fixtures=len(rows))))
