dpad_serial_bridge:
  ros__parameters:
    serial_port: "/dev/ttyUSB0"
    baud_rate: 115200
    dpad_mode: "axes"
    dpad_axis_horizontal: 6
    dpad_axis_vertical: 7
    dpad_axis_horizontal_sign: -1
    dpad_axis_vertical_sign: 1
