#pragma once
#include <array>
// Generated by training.wheel_align.generate_reference.
namespace neural_controller::align_reference {
inline constexpr double shift_seconds = 3.5;
inline constexpr double rise_seconds = 3;
inline constexpr double lift_seconds = 6.5;
inline constexpr double land_seconds = 6;
inline constexpr double recenter_seconds = 4;
inline constexpr double lower_seconds = 10;
inline constexpr double land_hip = 0.5;
inline constexpr std::array<double,2> active_residual{0.040000000000000001, 0.040000000000000001};
inline constexpr std::array<double,2> support_residual{0.10000000000000001, 0.14999999999999999};
inline constexpr std::array<double,2> active_speed{0.29999999999999999, 0.45000000000000001};
inline constexpr std::array<double,2> support_speed{0.34999999999999998, 0.45000000000000001};
inline constexpr std::array<double,2> active_accel{1.5, 2};
inline constexpr std::array<double,2> support_accel{1.5, 2};
inline constexpr std::array<std::array<double,8>,4> poses{{
  {{1.16890458, 1.0021502200000001, -1.2625986899999999, 0.28754656000000001, 1.0167859299999999, -0.16507621, -0.60319067999999998, -0.19620607000000001}},
  {{1.2625986899999999, -0.28754656000000001, -1.16890458, -1.0021502200000001, 0.60319067999999998, 0.19620607000000001, -1.0167859299999999, 0.16507621}},
  {{1, 0, -1, 0, 1, 1.05, -1, 0}},
  {{1, 0, -1, 0, 1, 0, -1, -1.05}},
}};
}
