#!/usr/bin/env python3
"""Check copied source bytes, policy selection and local include dependencies."""
import hashlib
import json
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
manifest = json.loads((root / 'IMPORT_MANIFEST.json').read_text())
for name, record in manifest['files'].items():
    data = (root / name).read_bytes()
    modification = manifest.get('integration_modifications', {}).get(name)
    expected_hash = modification['sha256'] if modification else record['copied_sha256']
    assert hashlib.sha256(data).hexdigest() == expected_hash, name
    assert record['source_sha256'] == record['copied_sha256'], name
    assert not data.startswith(b'version https://git-lfs.github.com/spec/v1'), name

for name, record in manifest['adapted_files'].items():
    assert hashlib.sha256((root / name).read_bytes()).hexdigest() == record['sha256'], name

package = root / 'ros2_ws/src/neural_controller'
for path in [*package.glob('src/*.cpp'), *package.glob('include/**/*.hpp')]:
    for inc in re.findall(r'#include\s*"([^"]+)"', path.read_text()):
        if inc == 'neural_controller/neural_controller_parameters.hpp':
            continue  # Generated by CMake.
        if inc.startswith('neural_controller/') or '/' not in inc:
            assert (path.parent / inc).is_file() or (package / 'include' / inc).is_file(), (path, inc)

latest = json.loads((root / 'policies/latest.json').read_text())
for selection in latest['policies'].values():
    assert hashlib.sha256((root / selection['policy_path']).read_bytes()).hexdigest() == selection['export_sha256']
expected = {'policy_walk_v2.json', 'policy_wheel.json', 'policy_leg_to_wheel.json',
            'policy_leg_lift_wheel.json', 'policy_wheel_to_walk_ready.json'}
assert {p.name for p in (package / 'launch').glob('policy*.json')} == expected
stanford = json.loads((root / 'STANFORD_IMPORT.json').read_text())
for name, expected_hash in stanford['current_sha256'].items():
    data = (root / name).read_bytes()
    assert hashlib.sha256(data).hexdigest() == expected_hash, name
    assert not data.startswith(b'version https://git-lfs.github.com/spec/v1'), name
print(f"PASS: {len(manifest['files'])} original import records and documented integration changes; "
      f"{len(stanford['current_sha256'])} Stanford files; selected exports and includes verified")
