"""Generate runtime reference constants; --check verifies without modifying files."""
from pathlib import Path
from . import configs as c

OUTPUT=Path(__file__).resolve().parents[2]/'ros2_ws/src/neural_controller/include/neural_controller/wheel_align_reference_data.hpp'

def render():
    lines=['#pragma once','#include <array>','// Generated by training.wheel_align.generate_reference.','namespace neural_controller::align_reference {']
    for name in ('SHIFT_SECONDS','RISE_SECONDS','LIFT_SECONDS','LAND_SECONDS','RECENTER_SECONDS','LOWER_SECONDS','LAND_HIP'):
        lines.append(f'inline constexpr double {name.lower()} = {getattr(c,name):.17g};')
    for name in ('ACTIVE_RESIDUAL','SUPPORT_RESIDUAL','ACTIVE_SPEED','SUPPORT_SPEED','ACTIVE_ACCEL','SUPPORT_ACCEL'):
        values=', '.join(f'{x:.17g}' for x in getattr(c,name))
        lines.append(f'inline constexpr std::array<double,2> {name.lower()}{{{values}}};')
    lines.append('inline constexpr std::array<std::array<double,8>,4> poses{{')
    lines.extend('  {{'+', '.join(f'{x:.17g}' for x in pose)+'}},' for pose in c.APEX_POSES)
    return '\n'.join(lines+['}};','}',''])

def main():
    import argparse
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');a=p.parse_args()
    if a.check:
        if OUTPUT.read_text()!=render():raise SystemExit('Reference constants differ: regenerate and review both runtimes.')
        print('PASS: runtime reference constants match')
    else:OUTPUT.write_text(render())

if __name__=='__main__':main()
